{
  "runnable": false,
  "phase": "repair",
  "error_type": "RuntimeError",
  "message": "Traceback (most recent call last):\n  File \"/home/wan00559/pipleline/utils/compile_and_run.py\", line 524, in compare_and_bench\n    ref_out,  _ = _run_once(ref_model,  inp, dev)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/pipleline/utils/compile_and_run.py\", line 127, in _run_once\n    out = model(*inp)\n          ^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 1751, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 1762, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/pipleline/KernelBench/temp/19_MobileNetV1.py\", line 58, in forward\n    x = self.model(x)\n        ^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 1751, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 1762, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/container.py\", line 240, in forward\n    input = module(input)\n            ^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 1751, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/module.py\", line 1762, in _call_impl\n    return forward_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/wan00559/miniconda3/envs/maxk/lib/python3.11/site-packages/torch/nn/modules/pooling.py\", line 756, in forward\n    return F.avg_pool2d(\n           ^^^^^^^^^^^^^\nRuntimeError: Given input size: (1024x4x4). Calculated output size: (1024x0x0). Output size is too small\n"
}